parent: .aws
description: >-
  Amazon Web Services (AWS) provider.

  Use the AWS provider to interact with the many resources supported by AWS.
  You must configure the provider with the proper credentials before you can use it.
source: providers.tf.json
address: provider
properties:
  assume_role_arn:
    value: null
    description: Amazon Resource Name (ARN) of the IAM Role to assume.
    ignore: true
  aws:
    properties:
      assume_role:
        properties:
          role_arn:
            value: '{_[assume_role_arn]}'
      default_tags:
        use: default_tags/tags
        properties:
          domain:
            use: Domain
            value: '{_[domain]}'
          environment:
            use: Environment
            value: '{_[environment]}'
          region:
            use: Region
            value: '{_[region]}'
          managed_by:
            use: ManagedBy
            value: terraform
      region:
        value: '{_[region]}'
