extends: .filter/tags
description: >-
  Provides details about a specific VPC.

  This resource can prove useful when a module accepts a vpc id as an input variable and needs to,
  for example, determine the CIDR block of that VPC.
path: vpc_name
source: vpc.tf.json
address: data/aws_vpc/this
properties:
  vpc_name:
    ignore: null
    required: true
    use: tags/Name
